apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-k8s-cicd
  namespace: nodejs-cicd
  labels:
    app: nodejs-k8s-cicd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-k8s-cicd
  template:
    metadata:
      labels:
        app: nodejs-k8s-cicd
    spec:
      containers:
        - name: nodejs-k8s-cicd
          image: aniket1805/nodejs-k8s-cicd:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "staging"
            - name: APP_VERSION
              value: "2.0.0-static-site"
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"